### ISSUE TITLE
Not working for me 

### ISSUE THREAD

**Issue by YellowAfro** [Najlepszy56/Krunker.io-Cheats#3]
I installed the mod , it works for my friend , but it doesnt work for me , what could i be doing wrong

**Comment by Najlepszy56** [comment]
1. Download this repo as a ZIP file.
2. Extract the ZIP file you just downloaded.
3. Go to chrome://extensions in your browser. Make sure you have Developer Mode activated.
4. Click "Load Unpacked" and select the subfolder named ChromeExtension which is in the extracted (called Krunker.io-Cheats-master.)
